site_name: HookeD

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.highlight
    - content.code.annotate
    - content.tabs.link
    - content.code.copy
  palette:
    - scheme: slate
      primary: custom
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  custom_dir: overrides

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Home: index.md
  - Routes: routes.md
  - Feed: feed.md
  - Trending: trending.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
