site_name: HookeD

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.highlight
    - content.code.annotate
    - content.tabs.link
    - content.code.copy
  palette:
    - scheme: slate
      primary: custom
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  custom_dir: overrides

extra_css:
  - assets/stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js

markdown_extensions:
  - pymdownx.arithmatex

nav:
  - Home: index.md
  - Feed: feed.md
  - Trending: trending.md
