name: Deploy Docs

on:
  push:
    branches: ['**']  # Match any branch
    paths:
      - 'hook-docs/**'

  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs Material
        run: pip install mkdocs-material

      - name: Deploy documentation to GitHub Pages
        working-directory: hook-docs
        run: mkdocs gh-deploy --force
